version: '3.9'

x-common: &common
  env_file:
    - .env
  volumes:
    - ./apps:/src/apps
    - ./paws:/src/paws
    - ./htmlcov:/src/htmlcov
    - ./scripts:/src/scripts

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    <<: *common
    depends_on:
      - database
    command: ["./scripts/wait-for-it.sh", "database:5432", "--", "./scripts/dev-entrypoint.sh"]
    ports:
      - "8010:8080"

  database:
    image: postgis/postgis:13-3.0-alpine
    container_name: paws-postgis
    restart: "no"
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data
    # For development management please use the following port: 50000
    ports:
      - "50000:5432"

volumes:
  pg_data:
